---
- name: "Adding UFW rules"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/ufw-configure-rule.yml"
  vars:
    rules:
      - {rule: "allow", proto: "udp", to_port: "67", comment: "Allow DHCP"}
